title: 聖潔復興記
description: I have to tell you something
permalink: /:title.html/
url: https://jawutzh.github.io/newsite
paginate: 8
paginate_path: "/page:num"
defaulthpurl: https://jawutzh.github.io/newsite/pics/default.jpg